apiVersion: v1
kind: Namespace
metadata:
  name: squid
  labels:
    name: squid
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: squid-vol-etc
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/microk8s/squid/etc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: squid-etc-pv-claim
  namespace: squid
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
---
kind: Service
apiVersion: v1
metadata:
  name: my-squid
  namespace: squid
  labels:
    app: my-squid
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.43.23
  ports:
    - name: proxy
      protocol: TCP
      port: 3128
      targetPort: 3128
  selector:
    app: my-squid
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-squid
  namespace: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-squid
  template:
    metadata:
      labels:
        app: my-squid
    spec:
      containers:
        - name: my-squid
          image: ellzap2/my-squid:latest
          ports:
            - containerPort: 3128
              protocol: TCP
              name: proxy
          env:
            - name: LOG_LEVEL
              value: info
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 64Mi
              cpu: "100m"
            limits:
              memory: 256Mi
          volumeMounts:
            - mountPath: /etc/squid
              name: squid-etc
      volumes:
        - name: squid-etc
          persistentVolumeClaim:
            claimName: squid-etc-pv-claim